less repeatin g code for logpdf / entropy / kldivergence
filtron/MarkovKernels.jl pull request #8
Opened 2022-08-12 13:53 UTC by filtron

2022-08-12 14:47 UTC, nathanaelbosch requested changes

2022-08-12 14:47 UTC, nathanaelbosch commented on src/normal/normal_generic.jl
> +kldivergence(N1::AbstractNormal{T}, N2::AbstractNormal{T}) where {T<:Number} =
Are there even `AbstractNormal{T}`s where `T` is not a `Number`? If not, you can simplify it again imo.

2022-08-12 14:47 UTC, nathanaelbosch commented on src/normal/normal_generic.jl
> +kldivergence(N1::AbstractNormal{T}, N2::AbstractNormal{T}) where {T<:Number} =
So according to https://github.com/filtron/MarkovKernels.jl/blob/70c29bd75e250dbb079bba95e63b7819da0e5384/src/normal/normal.jl#L6 it's always a number, so no need to specialize?

2022-08-12 14:47 UTC, nathanaelbosch commented on src/normal/normal.jl
> +    -_nscale(eltype(N)) * (logdet(_piconst(eltype(N)) * N.Σ) + norm_sqr(residual(N, x)))
```suggestion
logpdf(N::Normal{T}, x) where {T} =
    -_nscale(T) * (logdet(_piconst(T) * N.Σ) + norm_sqr(residual(N, x)))
```
JuliaFormatter might complain though so you'd need to fix that afterwards.

2022-08-12 14:47 UTC, nathanaelbosch commented on src/normal/normal.jl
> +    _nscale(eltype(N)) * (dim(N) * (log(_piconst(eltype(N))) + 1) + logdet(N.Σ))
Same as above:
```suggestion
entropy(N::Normal{T}) where {T} =
    _nscale(T) * (dim(N) * (log(_piconst(T) + 1) + logdet(N.Σ))
```

2022-08-12 15:00 UTC, filtron reviewed
seems fine.

2022-08-13 18:26 UTC, nathanaelbosch approved these changes

2022-08-14 10:15 UTC, merged